const http = require("http");
const url = require("url");
const fs = require("fs");
const path = require("path");
const port = 8000;

const server = http.createServer((req, res) => {
  console.log("request.url: ", req.url);

  const parsedUrl = url.parse(req.url, true);
//   console.log("parsedUrl: ", parsedUrl);
  const pathName = parsedUrl.pathname;
//   console.log("pathName: ", pathName);
  const query = parsedUrl.query;
//   console.log("query: ", query);

  if (pathName === "/") {
    const params = {
      studentName: "Glen Ru",
      studentID: 33724876,
      greeting: "Welcome to my page. Enjoy your time!",
    };
    return render("index", params, res);
  }

  if (pathName === "/about") {
    const params = {
      studentName: "Glen Ru",
      major: "BSc Computer Science",
      hobby: "Machine Learning and Full-Stack Development",
    };

    return render("about", params, res);
  }

  // 404 Page for unknown routes
  res.writeHead(404, { "Content-Type": "text/html; charset=utf-8" });
  res.end('<h1>404 Not Found</h1><a href="/">Go Home</a>');
});

// Function for rendering html template
function render(templateName, data, res) {
  const filePath = path.join(__dirname, "views", templateName + ".ejs");

  fs.readFile(filePath, "utf8", (err, content) => {
    if (err) {
      res.writeHead(500, { "Content-Type": "text/plain" });
      res.end("Server Error");
      return;
    }

    // Replace placeholders <%= key %> with values from the data object
    // The regex is generated by ChatGPT
    let rendered = content.replace(/<%=\s*(\w+)\s*%>/g, (_, key) => {
      return data[key] || "";
    });

    res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
    res.end(rendered);
  });
}

server.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});

